set_max_current:
  description: Sets the maximum current in Ampere of the Charger.
  fields:
    charger_name:
      description: name of the charger to update (if not specified all chargers will be changed)
      example: "charger1"
    max_current:
      description: current to be set (6-32)
      example: "16"
set_cable_lock_mode:
  description: Sets the cable lock mode of the Charger.
  fields:
    charger_name:
      description: name of the charger to update (if not specified all chargers will be changed)
      example: "charger1"
    cable_lock_mode:
      description: lock mode for the cable connected to the charger (0=locked while car connected, 1=unlock after charging finished, 2=always locked)
      example: "0"
set_absolute_max_current:
  description: Sets the absolute maximum current in Ampere of the Charger.
  fields:
    charger_name:
      description: name of the charger to update (if not specified all chargers will be changed)
      example: "charger1"
    charger_absolute_max_current:
      description: absolute maximum current to be set (6-32)
      example: "16"
set_charge_limit:
  description: Sets the charge limit in kWh of the Charger.
  fields:
    charger_name:
      description: name of the charger to update (if not specified all chargers will be changed)
      example: "charger1"
    charge_limit:
      description: charge limit in kWh example '2.5'
      example: "2.5"
